version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'Enzo'
    # Volumes store your data between container upgrades
    volumes:
       - 'C:\\Intel/pihole/2/:/etc/pihole/'
       - 'C:\\Intel/pihole/1/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    
    version: "2"
services:
    pyload:
      image: writl/pyload:0.4.20
      container_name: pyload
      ports:
        - 8000:8000
      environment:
        - UID=1000
        - GID=1000
      volumes:
        - 'C:\\Intel/pyload/conf:/opt/pyload/pyload-config'
        - 'C:\\Intel/pyload/data:/opt/pyload/Downloads'
